### PR TITLE
replace default export with a named export

### PR DESCRIPTION
**Pull request by n1ru4l**
See https://github.com/Codex-/cosmiconfig-typescript-loader/issues/36

This PR is built on top of https://github.com/Codex-/cosmiconfig-typescript-loader/pull/38 and show-cases how the import/require behavior is consistent on both platforms when switching from default imports to named imports.

See https://github.com/n1ru4l/cosmiconfig-typescript-loader/runs/8034633946 for a passing build

### CODE REVIEW

**Comment by n1ru4l** [comment]
@Codex- I pushed a commit for solving the eslint issues: https://github.com/Codex-/cosmiconfig-typescript-loader/pull/37/commits/3e9aa4d10ba854cee15cefded9c79c22c8e23bf2

I need approval for running the tests!

**Comment by Codex-** [comment]
No problem, I can take it from here :)

**Comment by n1ru4l** [comment]
@Codex- Thank you for your quick response and actions ❤️

**Comment by Codex-** [comment]
No problem, always happy to help out where I can :)

**Review by Codex- — APPROVED** [review]
Thanks for the PR :)

**Pull request merged**
